# ========== CONFIGURACION DEL SERVIDOR ==============
server.port=8084
spring.application.name=api-gateway

# ========== CONFIGURACION DE RUTAS DEL GATEWAY ==============

# ===== RUTA 1: Producto Service
spring.cloud.gateway.server.webflux.routes[0].id=producto-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://producto-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/producto/**

# ===== RUTA 2: Order Service
spring.cloud.gateway.server.webflux.routes[1].id=order-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://order-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/order/**

# ===== RUTA 3: Inventario Service
spring.cloud.gateway.server.webflux.routes[2].id=inventario-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://inventario-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/inventario/**

# ===== CONFIGURACIÓN DE EUREKA (CLIENTE)
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

# ===== PUNTO DE ENTRADA PARA CLIENTES KEYCLOAK
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/proyecto02-microservicios-realm