# ========== CONFIGURACION DEL SERVIDOR ===============
server.port=8761
spring.application.name=discovery-server

# ========== CONFIGURACION DEL REGISTRY EUREKA ==========
eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# ===== CONFIGURACION PROMETHEUS
management.endpoints.web.exposure.include=health,info,prometheus