# ========== CONFIGURACION DEL SERVIDOR ==============
server.port=8081
spring.application.name=producto-service

# ========== CONFIGURACION DE LA BASE DE DATOS ==========
spring.mongodb.uri=mongodb://localhost:27017/producto-service

# ========== CONFIGURACION DE EUREKA ==========
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

# ===== CONFIGURACION PROMETHEUS
management.endpoints.web.exposure.include=health,info,prometheus